# Hallo Hallo
sudo: required
services:
  - docker

before_install:
  - docker build -t itarch/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true itarch/frontend npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-663602868383"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

